name: tpm2-tools-alexmurray
version: 3.1.4
summary: TPM 2.0 utilities
description: |
  TPM (Trusted Platform Module) 2.0 tools based on tpm2-tss.

  NOTE: The tpm interface is not automatically connected and so needs to
  be manually connected after installation:

      snap connect tpm2-tools-alexmurray:tpm :tpm
confinement: strict
grade: stable
base: core18

apps:
  activatecredential:
    command: bin/tpm2_activatecredential
    plugs: [tpm]
  certify:
    command: bin/tpm2_certify
    plugs: [tpm]
  create:
    command: bin/tpm2_create
    plugs: [tpm]
  createpolicy:
    command: bin/tpm2_createpolicy
    plugs: [tpm]
  createprimary:
    command: bin/tpm2_createprimary
    plugs: [tpm]
  dictionarylockout:
    command: bin/tpm2_dictionarylockout
    plugs: [tpm]
  encryptdecrypt:
    command: bin/tpm2_encryptdecrypt
    plugs: [tpm]
  evictcontrol:
    command: bin/tpm2_evictcontrol
    plugs: [tpm]
  getcap:
    command: bin/tpm2_getcap
    plugs: [tpm]
  getmanufec:
    command: bin/tpm2_getmanufec
    plugs: [tpm]
  getpubak:
    command: bin/tpm2_getpubak
    plugs: [tpm]
  getpubek:
    command: bin/tpm2_getpubek
    plugs: [tpm]
  getrandom:
    command: bin/tpm2_getrandom
    plugs: [tpm]
  hash:
    command: bin/tpm2_hash
    plugs: [tpm]
  hmac:
    command: bin/tpm2_hmac
    plugs: [tpm]
  listpersistent:
    command: bin/tpm2_listpersistent
    plugs: [tpm]
  load:
    command: bin/tpm2_load
    plugs: [tpm]
  loadexternal:
    command: bin/tpm2_loadexternal
    plugs: [tpm]
  makecredential:
    command: bin/tpm2_makecredential
    plugs: [tpm]
  nvdefine:
    command: bin/tpm2_nvdefine
    plugs: [tpm]
  nvlist:
    command: bin/tpm2_nvlist
    plugs: [tpm]
  nvread:
    command: bin/tpm2_nvread
    plugs: [tpm]
  nvreadlock:
    command: bin/tpm2_nvreadlock
    plugs: [tpm]
  nvrelease:
    command: bin/tpm2_nvrelease
    plugs: [tpm]
  nvwrite:
    command: bin/tpm2_nvwrite
    plugs: [tpm]
  pcrevent:
    command: bin/tpm2_pcrevent
    plugs: [tpm]
  pcrextend:
    command: bin/tpm2_pcrextend
    plugs: [tpm]
  pcrlist:
    command: bin/tpm2_pcrlist
    plugs: [tpm]
  quote:
    command: bin/tpm2_quote
    plugs: [tpm]
  rc-decode:
    command: bin/tpm2_rc_decode
  readpublic:
    command: bin/tpm2_readpublic
    plugs: [tpm]
  rsadecrypt:
    command: bin/tpm2_rsadecrypt
    plugs: [tpm]
  rsaencrypt:
    command: bin/tpm2_rsaencrypt
    plugs: [tpm]
  send:
    command: bin/tpm2_send
    plugs: [tpm]
  sign:
    command: bin/tpm2_sign
    plugs: [tpm]
  startup:
    command: bin/tpm2_startup
    plugs: [tpm]
  takeownership:
    command: bin/tpm2_takeownership
    plugs: [tpm]
  unseal:
    command: bin/tpm2_unseal
    plugs: [tpm]
  verifysignature:
    command: bin/tpm2_verifysignature
    plugs: [tpm]

parts:
  tpm2-tss:
    plugin: autotools
    source: https://github.com/tpm2-software/tpm2-tss
    source-type: git
    source-tag: 2.2.3
    build-packages:
      - autoconf
      - autoconf-archive
      - libtool
      - gcc
      - g++
      - libc6-dev
      - doxygen
    prime:
      - -include

  tpm2-tools:
    plugin: autotools
    source: https://github.com/tpm2-software/tpm2-tools
    source-type: git
    source-tag: 3.1.4
    build-packages:
      - autoconf
      - autoconf-archive
      - pkg-config
      - libcmocka-dev
      - libcurl4-openssl-dev
      - libssl-dev
      - libtool
      - pandoc
    stage-packages:
      - libasn1-8-heimdal
      - libcurl3
      - libcurl4
      - libgssapi3-heimdal
      - libhcrypto4-heimdal
      - libheimbase1-heimdal
      - libheimntlm0-heimdal
      - libhx509-5-heimdal
      - libkrb5-26-heimdal
      - libldap-2.4-2
      - libnghttp2-14
      - libpsl5
      - libroken18-heimdal
      - librtmp1
      - libsasl2-2
      - libwind0-heimdal
    prime:
      - -include
    after:
      - tpm2-tss
