name: tpm2-tools-alexmurray
version: "5.2"
summary: TPM 2.0 utilities
description: |
  TPM (Trusted Platform Module) 2.0 tools based on tpm2-tss.

  NOTE: The tpm interface is not automatically connected and so needs to
  be manually connected after installation:

      snap connect tpm2-tools-alexmurray:tpm :tpm
confinement: strict
grade: stable
base: core18

apps:
  tpm2:
    command: bin/tpm2
    plugs: [tpm]
  certifyX509certutil:
    command: bin/tpm2_certifyX509certutil
    plugs: [tpm]
  checkquote:
    command: bin/tpm2_checkquote
    plugs: [tpm]
  eventlog:
    command: bin/tpm2_eventlog
    plugs: [tpm]
  print:
    command: bin/tpm2_print
    plugs: [tpm]
  rc-decode:
    command: bin/tpm2_rc_decode
    plugs: [tpm]
  activatecredential:
    command: bin/tpm2_activatecredential
    plugs: [tpm]
  certify:
    command: bin/tpm2_certify
    plugs: [tpm]
  changeauth:
    command: bin/tpm2_changeauth
    plugs: [tpm]
  changeeps:
    command: bin/tpm2_changeeps
    plugs: [tpm]
  changepps:
    command: bin/tpm2_changepps
    plugs: [tpm]
  clear:
    command: bin/tpm2_clear
    plugs: [tpm]
  clearcontrol:
    command: bin/tpm2_clearcontrol
    plugs: [tpm]
  clockrateadjust:
    command: bin/tpm2_clockrateadjust
    plugs: [tpm]
  create:
    command: bin/tpm2_create
    plugs: [tpm]
  createak:
    command: bin/tpm2_createak
    plugs: [tpm]
  createek:
    command: bin/tpm2_createek
    plugs: [tpm]
  createpolicy:
    command: bin/tpm2_createpolicy
    plugs: [tpm]
  setprimarypolicy:
    command: bin/tpm2_setprimarypolicy
    plugs: [tpm]
  createprimary:
    command: bin/tpm2_createprimary
    plugs: [tpm]
  dictionarylockout:
    command: bin/tpm2_dictionarylockout
    plugs: [tpm]
  duplicate:
    command: bin/tpm2_duplicate
    plugs: [tpm]
  getcap:
    command: bin/tpm2_getcap
    plugs: [tpm]
  gettestresult:
    command: bin/tpm2_gettestresult
    plugs: [tpm]
  encryptdecrypt:
    command: bin/tpm2_encryptdecrypt
    plugs: [tpm]
  evictcontrol:
    command: bin/tpm2_evictcontrol
    plugs: [tpm]
  flushcontext:
    command: bin/tpm2_flushcontext
    plugs: [tpm]
  getekcertificate:
    command: bin/tpm2_getekcertificate
    plugs: [tpm]
  getrandom:
    command: bin/tpm2_getrandom
    plugs: [tpm]
  gettime:
    command: bin/tpm2_gettime
    plugs: [tpm]
  hash:
    command: bin/tpm2_hash
    plugs: [tpm]
  hierarchycontrol:
    command: bin/tpm2_hierarchycontrol
    plugs: [tpm]
  hmac:
    command: bin/tpm2_hmac
    plugs: [tpm]
  import:
    command: bin/tpm2_import
    plugs: [tpm]
  incrementalselftest:
    command: bin/tpm2_incrementalselftest
    plugs: [tpm]
  load:
    command: bin/tpm2_load
    plugs: [tpm]
  loadexternal:
    command: bin/tpm2_loadexternal
    plugs: [tpm]
  makecredential:
    command: bin/tpm2_makecredential
    plugs: [tpm]
  nvdefine:
    command: bin/tpm2_nvdefine
    plugs: [tpm]
  nvextend:
    command: bin/tpm2_nvextend
    plugs: [tpm]
  nvincrement:
    command: bin/tpm2_nvincrement
    plugs: [tpm]
  nvreadpublic:
    command: bin/tpm2_nvreadpublic
    plugs: [tpm]
  nvread:
    command: bin/tpm2_nvread
    plugs: [tpm]
  nvreadlock:
    command: bin/tpm2_nvreadlock
    plugs: [tpm]
  nvundefine:
    command: bin/tpm2_nvundefine
    plugs: [tpm]
  nvwrite:
    command: bin/tpm2_nvwrite
    plugs: [tpm]
  nvwritelock:
    command: bin/tpm2_nvwritelock
    plugs: [tpm]
  nvsetbits:
    command: bin/tpm2_nvsetbits
    plugs: [tpm]
  pcrallocate:
    command: bin/tpm2_pcrallocate
    plugs: [tpm]
  pcrevent:
    command: bin/tpm2_pcrevent
    plugs: [tpm]
  pcrextend:
    command: bin/tpm2_pcrextend
    plugs: [tpm]
  pcrread:
    command: bin/tpm2_pcrread
    plugs: [tpm]
  pcrreset:
    command: bin/tpm2_pcrreset
    plugs: [tpm]
  policypcr:
    command: bin/tpm2_policypcr
    plugs: [tpm]
  policyauthorize:
    command: bin/tpm2_policyauthorize
    plugs: [tpm]
  policyauthorizenv:
    command: bin/tpm2_policyauthorizenv
    plugs: [tpm]
  policynv:
    command: bin/tpm2_policynv
    plugs: [tpm]
  policycountertimer:
    command: bin/tpm2_policycountertimer
    plugs: [tpm]
  policyor:
    command: bin/tpm2_policyor
    plugs: [tpm]
  policynamehash:
    command: bin/tpm2_policynamehash
    plugs: [tpm]
  policytemplate:
    command: bin/tpm2_policytemplate
    plugs: [tpm]
  policycphash:
    command: bin/tpm2_policycphash
    plugs: [tpm]
  policypassword:
    command: bin/tpm2_policypassword
    plugs: [tpm]
  policysigned:
    command: bin/tpm2_policysigned
    plugs: [tpm]
  policyticket:
    command: bin/tpm2_policyticket
    plugs: [tpm]
  policyauthvalue:
    command: bin/tpm2_policyauthvalue
    plugs: [tpm]
  policysecret:
    command: bin/tpm2_policysecret
    plugs: [tpm]
  policyrestart:
    command: bin/tpm2_policyrestart
    plugs: [tpm]
  policycommandcode:
    command: bin/tpm2_policycommandcode
    plugs: [tpm]
  policynvwritten:
    command: bin/tpm2_policynvwritten
    plugs: [tpm]
  policyduplicationselect:
    command: bin/tpm2_policyduplicationselect
    plugs: [tpm]
  policylocality:
    command: bin/tpm2_policylocality
    plugs: [tpm]
  quote:
    command: bin/tpm2_quote
    plugs: [tpm]
  readclock:
    command: bin/tpm2_readclock
    plugs: [tpm]
  readpublic:
    command: bin/tpm2_readpublic
    plugs: [tpm]
  rsadecrypt:
    command: bin/tpm2_rsadecrypt
    plugs: [tpm]
  rsaencrypt:
    command: bin/tpm2_rsaencrypt
    plugs: [tpm]
  send:
    command: bin/tpm2_send
    plugs: [tpm]
  selftest:
    command: bin/tpm2_selftest
    plugs: [tpm]
  setclock:
    command: bin/tpm2_setclock
    plugs: [tpm]
  shutdown:
    command: bin/tpm2_shutdown
    plugs: [tpm]
  sign:
    command: bin/tpm2_sign
    plugs: [tpm]
  certifycreation:
    command: bin/tpm2_certifycreation
    plugs: [tpm]
  nvcertify:
    command: bin/tpm2_nvcertify
    plugs: [tpm]
  startauthsession:
    command: bin/tpm2_startauthsession
    plugs: [tpm]
  startup:
    command: bin/tpm2_startup
    plugs: [tpm]
  stirrandom:
    command: bin/tpm2_stirrandom
    plugs: [tpm]
  testparms:
    command: bin/tpm2_testparms
    plugs: [tpm]
  unseal:
    command: bin/tpm2_unseal
    plugs: [tpm]
  verifysignature:
    command: bin/tpm2_verifysignature
    plugs: [tpm]
  setcommandauditstatus:
    command: bin/tpm2_setcommandauditstatus
    plugs: [tpm]
  getcommandauditdigest:
    command: bin/tpm2_getcommandauditdigest
    plugs: [tpm]
  getsessionauditdigest:
    command: bin/tpm2_getsessionauditdigest
    plugs: [tpm]
  geteccparameters:
    command: bin/tpm2_geteccparameters
    plugs: [tpm]
  ecephemeral:
    command: bin/tpm2_ecephemeral
    plugs: [tpm]
  commit:
    command: bin/tpm2_commit
    plugs: [tpm]
  ecdhkeygen:
    command: bin/tpm2_ecdhkeygen
    plugs: [tpm]
  ecdhzgen:
    command: bin/tpm2_ecdhzgen
    plugs: [tpm]
  zgen2phase:
    command: bin/tpm2_zgen2phase
    plugs: [tpm]
  sessionconfig:
    command: bin/tpm2_sessionconfig
    plugs: [tpm]
  getpolicydigest:
    command: bin/tpm2_getpolicydigest
    plugs: [tpm]

parts:
  tpm2-tss:
    plugin: autotools
    source: https://github.com/tpm2-software/tpm2-tss
    source-type: git
    source-tag: 3.1.0
    build-packages:
      - acl
      - autoconf
      - autoconf-archive
      - libtool
      - gcc
      - g++
      - libc6-dev
      - libgcrypt20-dev
      - libjson-c-dev
      - doxygen
      - libltdl-dev
    stage-packages:
      - libasn1-8-heimdal
      - libcurl4
      - libgssapi3-heimdal
      - libhcrypto4-heimdal
      - libheimbase1-heimdal
      - libheimntlm0-heimdal
      - libhx509-5-heimdal
      - libkrb5-26-heimdal
      - libldap-2.4-2
      - libnghttp2-14
      - libpsl5
      - libroken18-heimdal
      - librtmp1
      - libsasl2-2
      - libwind0-heimdal
    prime:
      - -include

  tpm2-tools:
    plugin: autotools
    source: https://github.com/tpm2-software/tpm2-tools
    source-type: git
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    build-packages:
      - autoconf
      - autoconf-archive
      - pkg-config
      - libcmocka-dev
      - libcurl4-openssl-dev
      - libssl-dev
      - libtool
      - pandoc
      - uuid-dev
    prime:
      - -include
    after:
      - tpm2-tss
